# travis build for APhotoManager
language: android
android:
  components:
    # https://github.com/travis-ci/travis-ci/issues/5036
    - tools
    - build-tools-23.0.2
    - android-21
    - add-on
    - extra

before_install:
# http://stackoverflow.com/questions/33820638/travis-yml-gradlew-permission-denied
 - chmod +x gradlew
 
 
script:
  - ./gradlew assemble pixymeta-j2se-demo:fatJar
  - java -jar pixymeta-j2se-demo/build/libs/pixymeta-j2se-demo-all.jar
  - ls -l build/testresults/

